---

- hosts: all
  vars_files:
    - inventory/vars/default.yml
    - vault/vault.yml
  vars:
    project_path: /var/www/nodejs
    release_path: "{{ project_path }}/releases/package"
    current_path: "{{ project_path }}/current"
    user_deploy: "vagrant"
    db_user: "{{db_user}}"
    db_name: recipefunnel
    db_password: "{{db_password}}"
    es_heap_size: 512m
  roles:
    - { role: apache, tags: [apache]}
    - { role: lets-encrypt, tags: [lets-encrypt]}
    - { role: deploy, tags: [deploy]}

  handlers:
    - name: Reload Apache
      become: yes
      become_method: sudo
      service:
          name: apache2
          state: reloaded

    - name: Restart Apache
      become: yes
      become_method: sudo
      service:
            name: apache2
            state: restarted
